apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  selector:
    matchLabels:
      app: login
  replicas: 1
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: saswsaho/mylogin
 
---
apiVersion: v1
kind: Service
metadata:
  name: login
spec:
  type: NodePort
  selector:
    app: login
  ports:
  - port: 80
    targetPort: 9001
    nodePort: 31000
